### ISSUE TITLE
Issue in Experiments.ipynb

### ISSUE THREAD

**Issue by rkarn** [sarashs/FPGA_AGI#2]
There is an issue:
1. You have commented out the line:
    os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY")
 But this is used in the parameters.py . It is throwing error. What is this key fore, it is not described.

**Comment by sarashs** [comment]
Hi,
This was origininally to test different search APIs. Serpapi is not actually used in the final solution. Tavily search is used instead.

**Comment by sarashs** [comment]
New commit resolves this issue
